import { defineField, defineType } from 'sanity';

const defaultSiteSettings = {
  title: 'Weronika Grzesiowska',
  description: 'Portfolio projektowe Weroniki Grzesiowskiej - grafika, ilustracja, branding.',
  heroTitleLines: ['Weronika', 'Grzesiowska'],
  heroGreeting: 'Cześć! ;-)',
  heroBio: [
    'Jestem absolwentką komunikacji wizerunkowej na UWr i projektantką z Wrocławia. Na co dzień zajmuję się grafiką komputerową i tworzeniem komunikacji.',
    'Lubię gołębie.',
  ],
  projectsTitle: 'Projekty',
  contactName: 'Weronika Grzesiowska',
  contactEmail: 'weronikagrzesiowska@gmail.com',
  contactPhone: '+48 732 252 434',
  aboutTitle: 'O mnie',
  aboutContent: [
    'Jestem projektantką z Wrocławia. Zajmuję się grafiką komputerową, identyfikacją wizualną i komunikacją marek.',
    'Ta treść jest placeholderem developerskim i może zostać zastąpiona w Sanity Studio.',
  ],
  cvTitle: 'CV',
  cvContent: [
    'CV może być zarządzane z poziomu Sanity jako opis tekstowy oraz opcjonalne pliki PDF.',
  ],
};

export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: 'Ustawienia strony',
  type: 'document',
  groups: [
    { name: 'seo', title: 'SEO' },
    { name: 'hero', title: 'Hero', default: true },
    { name: 'projects', title: 'Projekty' },
    { name: 'contact', title: 'Kontakt' },
    { name: 'about', title: 'O mnie' },
    { name: 'cv', title: 'CV' },
  ],
  initialValue: defaultSiteSettings,
  fields: [
    defineField({
      name: 'title',
      title: 'Tytuł strony',
      type: 'string',
      group: 'seo',
      initialValue: defaultSiteSettings.title,
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Opis SEO',
      type: 'text',
      group: 'seo',
      rows: 3,
      initialValue: defaultSiteSettings.description,
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'heroTitleLines',
      title: 'Nagłówek hero',
      type: 'array',
      group: 'hero',
      description: 'Każdy element tablicy renderuje się jako osobna linia nagłówka.',
      of: [{ type: 'string' }],
      initialValue: defaultSiteSettings.heroTitleLines,
      validation: Rule => Rule.required().min(1),
    }),
    defineField({
      name: 'heroGreeting',
      title: 'Przywitanie w hero',
      type: 'string',
      group: 'hero',
      initialValue: defaultSiteSettings.heroGreeting,
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'heroBio',
      title: 'Akapity bio w hero',
      type: 'array',
      group: 'hero',
      of: [{ type: 'text', rows: 3 }],
      initialValue: defaultSiteSettings.heroBio,
      validation: Rule => Rule.required().min(1),
    }),
    defineField({
      name: 'projectsTitle',
      title: 'Tytuł sekcji projektów',
      type: 'string',
      group: 'projects',
      initialValue: defaultSiteSettings.projectsTitle,
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'contactName',
      title: 'Kontakt: imię i nazwisko',
      type: 'string',
      group: 'contact',
      initialValue: defaultSiteSettings.contactName,
    }),
    defineField({
      name: 'contactEmail',
      title: 'Kontakt: email',
      type: 'string',
      group: 'contact',
      initialValue: defaultSiteSettings.contactEmail,
      validation: Rule => Rule.email(),
    }),
    defineField({
      name: 'contactPhone',
      title: 'Kontakt: telefon',
      type: 'string',
      group: 'contact',
      initialValue: defaultSiteSettings.contactPhone,
    }),
    defineField({
      name: 'aboutTitle',
      title: 'O mnie: tytuł',
      type: 'string',
      group: 'about',
      initialValue: defaultSiteSettings.aboutTitle,
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'aboutContent',
      title: 'O mnie: treść',
      type: 'array',
      group: 'about',
      of: [{ type: 'text', rows: 4 }],
      initialValue: defaultSiteSettings.aboutContent,
    }),
    defineField({
      name: 'cvTitle',
      title: 'CV: tytuł',
      type: 'string',
      group: 'cv',
      initialValue: defaultSiteSettings.cvTitle,
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'cvContent',
      title: 'CV: treść',
      type: 'array',
      group: 'cv',
      of: [{ type: 'text', rows: 4 }],
      initialValue: defaultSiteSettings.cvContent,
    }),
    defineField({
      name: 'cvFile',
      title: 'CV: plik PDF po polsku',
      type: 'file',
      group: 'cv',
      options: { accept: '.pdf' },
    }),
    defineField({
      name: 'cvFileEn',
      title: 'CV: plik PDF po angielsku',
      type: 'file',
      group: 'cv',
      options: { accept: '.pdf' },
    }),
  ],
  preview: {
    prepare() {
      return {
        title: 'Ustawienia strony',
      };
    },
  },
});
